Changes made
hackthepart/TheFirstAvenger pull request #20
Opened 2017-12-17 07:38 UTC by sidmojo

2017-12-17 08:20 UTC, nikilagar requested changes
Use meaningful variable names.

2017-12-17 08:20 UTC, nikilagar commented
Give a title to your PR.

2017-12-17 11:39 UTC, nikilagar requested changes

2017-12-17 11:39 UTC, nikilagar commented on TicTacToe/src/tictactoe/GameWindow.java
> +            jLabel2.setText(pl1name);
Change the control names too!!! Rest seem fine.

2017-12-18 09:55 UTC, sidmojo commented
Control names have been changed.

2017-12-23 08:41 UTC, closed without merging