Fix #1
hackthepart/TheFirstAvenger pull request #4
Opened 2017-12-15 11:23 UTC by iosdev474

2017-12-15 12:00 UTC, iosdev474 commented
closing due to adding all 3 features in other pull request

2017-12-15 13:27 UTC, iosdev474 commented
please ignore commit messages :p and fix #1 , fix #6 and 
Added Feature 1,2,3
Added Features:
	Player should have different names
	Player should have different symbols
	Player's name can not be blank
	Player's symbol can not be blank
	Player can choose Alphabets,numbers etc as their symbol

2017-12-15 17:33 UTC, urdarinda commented
@nikilagar @iosdev474 My eyes hurt by seeing the title and the commit messages. Please fix :-1:

2017-12-15 17:38 UTC, nikilagar requested changes

2017-12-15 17:38 UTC, nikilagar commented on TicTacToe/src/tictactoe/GameWindow.java
> +    int moved[][]=new int[3][3];
Why not boolean.

2017-12-15 17:38 UTC, nikilagar commented on TicTacToe/src/tictactoe/GameWindow.java
> +        if(draw==true)
No need to compare with true. If(draw) would suffice!!!

2017-12-15 17:38 UTC, nikilagar commented on TicTacToe/src/tictactoe/GameWindow.java
> +    private void nameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextfieldActionPerformed
Unnecessary function.

2017-12-15 17:38 UTC, nikilagar commented on TicTacToe/src/tictactoe/GameWindow.java
> +    if(!nameTextfield.getText().equals(""))
Indent the code.

2017-12-15 17:38 UTC, nikilagar commented on TicTacToe/src/tictactoe/GameWindow.java
> +    if(!nameTextfield.getText().equals(""))
Indent the code.

2017-12-16 04:44 UTC, iosdev474 commented on TicTacToe/src/tictactoe/GameWindow.java
> +    int moved[][]=new int[3][3];
ok

2017-12-16 04:45 UTC, iosdev474 commented on TicTacToe/src/tictactoe/GameWindow.java
> +        if(draw==true)
ok

2017-12-16 04:45 UTC, iosdev474 commented on TicTacToe/src/tictactoe/GameWindow.java
> +    private void nameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextfieldActionPerformed
removed

2017-12-16 04:45 UTC, iosdev474 commented on TicTacToe/src/tictactoe/GameWindow.java
> +    if(!nameTextfield.getText().equals(""))
done indenting

2017-12-16 04:45 UTC, iosdev474 commented on TicTacToe/src/tictactoe/GameWindow.java
> +    if(!nameTextfield.getText().equals(""))
done indenting

2017-12-16 16:24 UTC, iosdev474 commented
adding another feature so closing request :-)

2017-12-16 16:25 UTC, closed without merging